<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="wsb-007-74" failures="2" tests="2" name="testExpectedArithmeticException" time="0.002" errors="0" timestamp="2022-01-30T17:05:42 MSK">
  <testcase classname="CheckingWorkMethodTestThrowsArithmExceptionTest" name="testExpectedArithmeticException" time="0.001">
    <failure type="org.testng.TestException" message="
Method CheckingWorkMethodTestThrowsArithmExceptionTest.testExpectedArithmeticException(java.lang.String,int,double)[pri:0, instance:CheckingWorkMethodTestThrowsArithmExceptionTest@291ae] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method CheckingWorkMethodTestThrowsArithmExceptionTest.testExpectedArithmeticException(java.lang.String,int,double)[pri:0, instance:CheckingWorkMethodTestThrowsArithmExceptionTest@291ae] should have thrown an exception of type class java.lang.ArithmeticException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testExpectedArithmeticException -->
  <testcase classname="CheckingWorkMethodTestThrowsArithmExceptionTest" name="testExpectedArithmeticException" time="0.0">
    <failure type="org.testng.TestException" message="
Method CheckingWorkMethodTestThrowsArithmExceptionTest.testExpectedArithmeticException(java.lang.String,int,double)[pri:0, instance:CheckingWorkMethodTestThrowsArithmExceptionTest@291ae] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method CheckingWorkMethodTestThrowsArithmExceptionTest.testExpectedArithmeticException(java.lang.String,int,double)[pri:0, instance:CheckingWorkMethodTestThrowsArithmExceptionTest@291ae] should have thrown an exception of type class java.lang.ArithmeticException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testExpectedArithmeticException -->
</testsuite> <!-- testExpectedArithmeticException -->
